FROM 111664719423.dkr.ecs.us-east-1.amazonaws.com/base:latest 
ARG REVISION
ARG SOURCE
LABEL org.opencontainers.image.revision=$REVISION
LABEL org.opencontainers.image.source=$SOURCE
CMD ["cat", "dog.json"]

